export type { CompressConfig, FuzzyDedupConfig, OllamaExtractionConfig } from "./config";
export { DEFAULT_OLLAMA_EXTRACTION } from "./config";
export { compressLs } from "./strategies/ls";
export { compressTestOutput } from "./strategies/test";
export { compressGrep } from "./strategies/grep";
export { compressGitStatus, compressGitLog, compressGitDiff } from "./strategies/git";
export { compressGeneric, compressRelevantGeneric } from "./strategies/generic";
export { compressByType, detectOutputType } from "./output-types";
export { classifyShape, applyShapeCompression } from "./shape";
export { trimByRelevance } from "./relevance";
export { tryDeltaCompression, updateDeltaCache } from "./delta";
export { addContentDedup, trigramJaccard } from "./dedup";
export { isSignalOutput, stripAnsi, contentPreview, getCommandPrefix, smartFilter, scoreLine, extractQueryTerms, SIGNAL_WORDS } from "./utils";
export { ollamaExtract } from "./ollama-extract";
