export type { CompressConfig, FuzzyDedupConfig } from "./config";
export { compressLs } from "./strategies/ls";
export { compressTestOutput } from "./strategies/test";
export { compressGrep } from "./strategies/grep";
export { compressGitStatus, compressGitLog, compressGitDiff } from "./strategies/git";
export { compressGeneric } from "./strategies/generic";
export { classifyShape, applyShapeCompression } from "./shape";
export { trimByRelevance } from "./relevance";
export { tryDeltaCompression, updateDeltaCache } from "./delta";
export { addContentDedup, trigramJaccard } from "./dedup";
export { isSignalOutput, stripAnsi, contentPreview, getCommandPrefix } from "./utils";
